-- analytics.sql
-- ---------------------------------------------------------------------
-- Production-quality analytics queries against the olist_analytics
-- star schema and governance/control tables.
-- Section A = Business Analytics (Power BI Dashboard 1)
-- Section B = Data Quality / Governance Analytics (Power BI Dashboard 2)
-- ---------------------------------------------------------------------

\c olist_analytics

-- ======================================================================
-- SECTION A — BUSINESS ANALYTICS
-- ======================================================================

-- A1. Total revenue (sum of total_value across all order items)
SELECT ROUND(SUM(total_value), 2) AS total_revenue
FROM fact_sales;

-- A2. Monthly revenue trend
SELECT
    d.year,
    d.month,
    d.month_name,
    ROUND(SUM(f.total_value), 2) AS monthly_revenue,
    COUNT(DISTINCT f.order_id) AS order_count
FROM fact_sales f
JOIN dim_date d ON f.date_key = d.date_key
GROUP BY d.year, d.month, d.month_name
ORDER BY d.year, d.month;

-- A3. Order volume (distinct orders) and average order value
WITH order_totals AS (
    SELECT order_id, SUM(total_value) AS order_value
    FROM fact_sales
    GROUP BY order_id
)
SELECT
    COUNT(*) AS total_orders,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM order_totals;

-- A4. Revenue by product category (English name)
SELECT
    COALESCE(p.product_category_name_english, 'uncategorized') AS category,
    ROUND(SUM(f.total_value), 2) AS revenue,
    COUNT(*) AS items_sold,
    RANK() OVER (ORDER BY SUM(f.total_value) DESC) AS revenue_rank
FROM fact_sales f
JOIN dim_product p ON f.product_key = p.product_key
GROUP BY category
ORDER BY revenue DESC;

-- A5. Revenue by customer state
SELECT
    c.customer_state,
    ROUND(SUM(f.total_value), 2) AS revenue,
    COUNT(DISTINCT f.order_id) AS orders
FROM fact_sales f
JOIN dim_customer c ON f.customer_key = c.customer_key
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- A6. Seller performance — revenue, order count, avg delivery delay
SELECT
    s.seller_id,
    s.seller_state,
    ROUND(SUM(f.total_value), 2) AS revenue,
    COUNT(DISTINCT f.order_id) AS orders_fulfilled,
    RANK() OVER (ORDER BY SUM(f.total_value) DESC) AS seller_rank
FROM fact_sales f
JOIN dim_seller s ON f.seller_key = s.seller_key
GROUP BY s.seller_id, s.seller_state
ORDER BY revenue DESC
LIMIT 20;

-- A7. Delivery performance — average delivery days and late-delivery rate
SELECT
    COUNT(*) AS delivered_orders,
    ROUND(AVG(EXTRACT(DAY FROM (order_delivered_customer_date - order_purchase_timestamp))), 2)
        AS avg_delivery_days,
    ROUND(
        100.0 * SUM(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 ELSE 0 END)
        / NULLIF(COUNT(*), 0), 2
    ) AS late_delivery_pct
FROM stg_orders
WHERE order_status = 'delivered'
  AND order_delivered_customer_date IS NOT NULL;

-- A8. Order status breakdown
SELECT
    order_status,
    COUNT(*) AS order_count,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS pct_of_orders
FROM stg_orders
GROUP BY order_status
ORDER BY order_count DESC;


-- ======================================================================
-- SECTION B — DATA QUALITY / GOVERNANCE ANALYTICS
-- ======================================================================
-- Note: issue_register / quality_scorecard / reconciliation results are
-- generated by the Python pipeline (reports/*.json, reports/issue_register.csv)
-- and can be loaded into PostgreSQL as `issue_register` for direct SQL
-- querying and Power BI connectivity. The queries below assume an
-- `issue_register` table with columns matching issue_register.csv.

-- B1. Missing-value rate by dataset (from staged tables)
SELECT
    'orders' AS dataset,
    ROUND(100.0 * COUNT(*) FILTER (WHERE order_delivered_customer_date IS NULL AND order_status = 'delivered')
        / NULLIF(COUNT(*), 0), 3) AS missing_value_rate_pct
FROM stg_orders;

-- B2. Duplicate rate check (composite key collisions in order_items)
SELECT
    COUNT(*) AS total_rows,
    COUNT(*) - COUNT(DISTINCT (order_id, order_item_id)) AS duplicate_key_rows
FROM stg_order_items;

-- B3. Validation failures (from issue_register table)
SELECT rule_id, dataset, field, severity, affected_records, status
FROM issue_register
WHERE affected_records > 0
ORDER BY
    CASE severity
        WHEN 'Critical' THEN 1 WHEN 'High' THEN 2
        WHEN 'Medium' THEN 3 WHEN 'Low' THEN 4 ELSE 5
    END,
    affected_records DESC;

-- B4. Issues by severity
SELECT severity, COUNT(*) AS issue_count, SUM(affected_records) AS total_affected_records
FROM issue_register
WHERE status = 'Open'
GROUP BY severity
ORDER BY total_affected_records DESC;

-- B5. Issues by dataset
SELECT dataset, COUNT(*) AS issue_count, SUM(affected_records) AS total_affected_records
FROM issue_register
WHERE status = 'Open'
GROUP BY dataset
ORDER BY total_affected_records DESC;

-- B6. Open vs. resolved issues
SELECT status, COUNT(*) AS issue_count
FROM issue_register
GROUP BY status;

-- B7. Quality score by dataset (from quality_scorecard, loaded as `quality_scorecard`)
--     quality_scorecard(dataset, dimension, score_pct)
SELECT dataset, ROUND(AVG(score_pct), 2) AS dataset_quality_score_pct
FROM quality_scorecard
GROUP BY dataset
ORDER BY dataset_quality_score_pct DESC;

-- B8. Reconciliation status (from reconciliation_report, loaded as `reconciliation_checks`)
SELECT check, dataset, status, variance_pct
FROM reconciliation_checks
ORDER BY
    CASE status WHEN 'FAIL' THEN 1 WHEN 'WARNING' THEN 2 ELSE 3 END;
